package lista01.utils;
/**
 * Pedro Henrique Pereira Alba,
 * Renato Constancion Filho
 */

public class GeraNomeRandomico {
	
	
	public static String geraNome(char sexo){
		return (sexo == 'm') ? geraNomeMasculino() : geraNomeFeminino();
	}

	private static String geraNomeMasculino(){
//		http://exame.abril.com.br/brasil/os-100-nomes-de-bebes-mais-populares-no-brasil-em-2016/
		String nomeMasculino[] = {
				"Miguel",
				"Arthur",
				"Davi",
				"Bernardo",
				"Heitor",
				"Gabriel",
				"Pedro",
				"Lorenzo",
				"Lucas",
				"Matheus",
				"Enzo",
				"Theo",
				"Benjamin",
				"Rafael",
				"Nicolas",
				"Guilherme",
				"Gustavo",
				"Samuel",
				"Henrique",
				"Felipe",
				"Murilo",
				"Joaquim",
				"João Pedro",
				"João Miguel",
				"Enzo Gabriel",
				"Daniel",
				"Isaac",
				"Pietro",
				"Pedro Henrique",
				"Lucca",
				"Eduardo",
				"Benício",
				"Leonardo",
				"Vitor",
				"João Lucas",
				"Bryan",
				"João",
				"Cauã",
				"Davi Lucca",
				"Anthony",
				"Vicente",
				"Vinícius",
				"Caio",
				"Antônio",
				"Davi Lucas",
				"Bento",
				"João Gabriel",
				"João Vitor",
				"Noah",
				"Francisco",
				"Calebe",
				"Gael",
				"Emanuel",
				"Ian",
				"Luiz Miguel",
				"Enrico",
				"Thiago",
				"Augusto",
				"Otávio",
				"João Guilherme",
				"Ryan",
				"Yuri",
				"Levi",
				"Vitor Hugo",
				"Erick",
				"Bruno",
				"Nathan",
				"Raul",
				"Henry",
				"Davi Luiz",
				"Luiz Felipe",
				"Thomas",
				"Rodrigo",
				"Davi Miguel",
				"André",
				"Fernando",
				"Alexandre",
				"Pedro Lucas",
				"Breno",
				"Arthur Miguel",
				"Carlos Eduardo",
				"Kaique",
				"Yago",
				"Kauê",
				"Luan",
				"Igor",
				"Luiz Henrique",
				"Luiz Gustavo",
				"Arthur Gabriel",
				"Mathias",
				"Lucas Gabriel",
				"Pedro Miguel",
				"Arthur Henrique",
				"Ruan",
				"Tomás",
				"Danilo",
				"Enzo Miguel",
				"Luiz Otávio",
				"Ricardo",
				"Oliver"
		};
		return nomeMasculino[(int) (Math.random() * (nomeMasculino.length))];
	}
	
	private static String geraNomeFeminino(){
//		http://exame.abril.com.br/brasil/os-100-nomes-de-bebes-mais-populares-no-brasil-em-2016/
		String nomeFeminino[] = {
				"Alice",
				"Sophia",
				"Laura",
				"Valentina",
				"Helena",
				"Isabella",
				"Manuela",
				"Júlia",
				"Luiza",
				"Lívia",
				"Giovanna",
				"Maria Luiza",
				"Heloísa",
				"Maria Eduarda",
				"Maria Clara",
				"Lara",
				"Lorena",
				"Beatriz",
				"Mariana",
				"Melissa",
				"Cecília",
				"Ana Clara",
				"Ana Júlia",
				"Yasmin",
				"Maria Júlia",
				"Isadora",
				"Rafaela",
				"Emanuelly",
				"Ana Luiza",
				"Esther",
				"Lavínia",
				"Sarah",
				"Isabelly",
				"Elisa",
				"Eloah",
				"Nicole",
				"Maria Alice",
				"Gabriela",
				"Maria",
				"Rebeca",
				"Letícia",
				"Clara",
				"Marina",
				"Isis",
				"Ana",
				"Alícia",
				"Liz",
				"Antonella",
				"Maria Cecília",
				"Agatha",
				"Catarina",
				"Ana Laura",
				"Larissa",
				"Ana Beatriz",
				"Maria Fernanda",
				"Maitê",
				"Luna",
				"Olívia",
				"Vitória",
				"Bianca",
				"Laís",
				"Allana",
				"Maria Valentina",
				"Emilly",
				"Ana Sophia",
				"Clarice",
				"Milena",
				"Pietra",
				"Fernanda",
				"Carolina",
				"Amanda",
				"Maria Vitória",
				"Maria Helena",
				"Eduarda",
				"Malu",
				"Maria Sophia",
				"Stella",
				"Camila",
				"Maya",
				"Gabrielly",
				"Mirella",
				"Mariah",
				"Ana Lívia",
				"Maria Flor",
				"Ayla",
				"Isabel",
				"Sophie",
				"Giulia",
				"Luana",
				"Bruna",
				"Ana Vitória",
				"Joana",
				"Maria Laura",
				"Maria Isis",
				"Louise",
				"Pérola",
				"Natália",
				"Ana Cecília",
				"Aurora",
				"Bárbara",
		};
		return nomeFeminino[(int) (Math.random() * (nomeFeminino.length))];
	}
	
}
