package listas.lista03.exercicio02;

import java.util.LinkedList;
import java.util.List;
import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;

public class VeiculoFactory {

	public static VeiculoFactory instance = new VeiculoFactory();
	public static String[] letras = {"A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"};
	public static String[] veiculo = {"Chevrolet Captiva",
			"Chevrolet Celta  ",
			"Chevrolet Classic",
			"Chevrolet Cobalt ",
			"Chevrolet Cruze  ",
			"Chevrolet Cruze S",
			"Chevrolet Montana",
			"Chevrolet Onix   ",
			"Chevrolet Prisma ",
			"Chevrolet S10    ",
			"Chevrolet Sonic H",
			"Chevrolet Sonic S",
			"Chevrolet Spin   ",
			"Chevrolet Tracker",
			"Chevrolet TrailBl",
			"Chevrolet Camaro ",
			"Chevrolet Agile  ",
			"Hyundai HB20S    ",
			"Nissan Altima    ",
			"Volkswagen Amarok",
			"Volkswagen CC / P",
			"Volkswagen CrossF",
			"Volkswagen Fox   ",
			"Volkswagen Fusca ",
			"Volkswagen Gol   ",
			"Volkswagen Golf  ",
			"Volkswagen Jetta ",
			"Volkswagen Jetta ",
			"Volkswagen Kombi ",
			"Volkswagen Passat",
			"Volkswagen Passat",
			"Volkswagen Polo  ",
			"Volkswagen Polo S",
			"Volkswagen Saveir",
			"Volkswagen SpaceC",
			"Volkswagen SpaceF",
			"Volkswagen Tiguan",
			"Volkswagen Touare",
			"Volkswagen Voyage",
			"Peugeot 207      ",
			"Peugeot 207 Sedan",
			"Peugeot 207 SW   ",
			"Peugeot 3008     ",
			"Peugeot 308      ",
			"Peugeot 308 CC   ",
			"Peugeot 408      ",
			"Peugeot 508      ",
			"Peugeot Boxer    ",
			"Peugeot Hoggar   ",
			"Peugeot Partner  ",
			"Peugeot RCZ      ",
			"Citroën DS4      ",
			"Citroën DS5      ",
			"Volvo V60        ",
			"Toyota Prius     ",
			"Toyota Etios Hatc",
			"Toyota Etios Seda",
			"Hyundai Equus    ",
			"Hyundai Genesis  ",
			"Hyundai HB20     ",
			"Hyundai HB20X    ",
			"Fiat 500         ",
			"Fiat Bravo       ",
			"Fiat Doblò       ",
			"Fiat Doblò Cargo ",
			"Fiat Ducato      ",
			"Fiat Fiorino Furg",
			"Fiat Freemont    ",
			"Fiat Grand Siena ",
			"Fiat Idea        ",
			"Fiat Linea       ",
			"Fiat Mille       ",
			"Fiat Palio       ",
			"Fiat Palio Weeken",
			"Fiat Punto       ",
			"Fiat Siena       ",
			"Fiat Strada      ",
			"Fiat Uno         ",
			"Fiat Uno Furgão  ",
			"Citroën DS3      ",
			"Toyota Etios     ",
			"Ford Courier (pic",
			"Ford EcoSport    ",
			"Ford Edge        ",
			"Ford Fiesta      ",
			"Ford Fiesta Sedan",
			"Ford Focus       ",
			"Ford Focus Sedan ",
			"Ford Fusion (Amér",
			"Ford Ka          ",
			"Ford Ranger      ",
			"Ford Transit     ",
			"JAC J3           ",
			"JAC J3 Turin     ",
			"JAC J5           ",
			"JAC J6           ",
			"JAC J2           ",
			"Citroën C3       ",
			"Citroën C3 Aircro",
			"Citroën C3 Picass",
			"Citroën C4       ",
			"Citroën C4 Pallas",
			"Citroën C4 Picass",
			"Citroën C5       ",
			"Citroën C5 Tourer",
			"Citroën Grand C4 ",
			"Citroën Jumper   ",
			"Citroën Xsara Pic",
			"Nissan Versa     ",
			"Volvo C30        ",
			"Volvo S60        ",
			"Volvo XC60       ",
			"Volvo XC90       ",
			"Hyundai Veloster ",
			"Hyundai Elantra  ",
			"Renault Duster   ",
			"Nissan Frontier  ",
			"Nissan Grand Livi",
			"Nissan Livina    ",
			"Nissan March     ",
			"Nissan Sentra    ",
			"Nissan Tiida     ",
			"Nissan Tiida Seda",
			"Suzuki Jimny     ",
			"Suzuki Grand Vita",
			"Suzuki SX4       ",
			"Honda Accord     ",
			"Honda City       ",
			"Honda Civic      ",
			"Honda CR-V       ",
			"Honda Fit        ",
			"Renault Clio     ",
			"Renault Sandero  ",
			"Renault Logan    ",
			"Renault Symbol   ",
			"Renault Grand Tou",
			"Renault Fluence  ",
			"Renault Kangoo   ",
			"Renault Master   ",
			"Hyundai Tucson   ",
			"Hyundai ix35     ",
			"Hyundai i30      ",
			"Hyundai i30 CW   ",
			"Hyundai Sonata   ",
			"Hyundai HR       ",
			"Hyundai Santa Fe ",
			"Hyundai Veracruz ",
			"Hyundai Azera    ",
			"Toyota RAV4      ",
			"Toyota Hilux SW4 ",
			"Toyota Hilux     ",
			"Toyota Corolla   ",
			"Toyota Camry     "};
	public static String[] nomes = {
			"Abda S",
			"Abigai",
			"Acácia",
			"Adalgi",
			"Adeilc",
			"Adelai",
			"Adélia",
			"Adrian",
			"Agnes ",
			"Aida S",
			"Aidée ",
			"Aime S",
			"Aimée ",
			"Aira S",
			"Aisla ",
			"Alana ",
			"Alanis",
			"Alaíde",
			"Alba D",
			"Albert",
			"Alcina",
			"Alcion",
			"Aldete",
			"Alécya",
			"Alessa",
			"Alena ",
			"Alenis",
			"Aléssi",
			"Alexa ",
			"Alexan",
			"Alice ",
			"Alicia",
			"Aline ",
			"Alison",
			"Alrian",
			"Alzira",
			"Amalia",
			"Amanda",
			"Amelia",
			"Améric",
			"Ana   ",
			"Anabel",
			"Anabel",
			"Ananda",
			"Anastá",
			"Andréa",
			"Andres",
			"Anete ",
			"Angela",
			"Angéli",
			"Angeli",
			"Anita ",
			"Antoni",
			"Antoni",
			"Antuér",
			"Aparec",
			"Araci ",
			"Ariane",
			"Ariene",
			"Arisla",
			"Arissa",
			"Arlett",
			"Armind",
			"Aryana",
			"Astrid",
			"Audrey",
			"Adelin",
			"Assunç",
			"Audrey",
			"August",
			"Aura  ",
			"Aureli",
			"Aarão ",
			"Abdala",
			"Abdemi",
			"Abel  ",
			"Abelar",
			"Abraão",
			"Acácio",
			"Adalbe",
			"Adamas",
			"Adão  ",
			"Adauto",
			"Ademar",
			"Adib  ",
			"Adolfo",
			"Adrian",
			"Aécio ",
			"Aeling",
			"Agnald",
			"Alan  ",
			"Alberi",
			"Albert",
			"Alceu ",
			"Alcir ",
			"Aldo  ",
			"Alenca",
			"Alessa",
			"Alessi",
			"Alex  ",
			"Alexsa",
			"Alfred",
			"Alfeu ",
			"Almir ",
			"Aluisi",
			"Alvaro",
			"Altami",
			"Amadeu",
			"Amauri",
			"Améric",
			"Amin  ",
			"Amânci",
			"Amilca",
			"Amir  ",
			"Amon  ",
			"Anat  ",
			"André ",
			"Andrew",
			"Angel ",
			"Angelo",
			"Anibal",
			"Anselm",
			"Antero",
			"Anthon",
			"Antoni",
			"Arlind",
			"Apolo ",
			"Aquile",
			"Aristo",
			"Armand",
			"Arnald",
			"Arthur",
			"Ary   ",
			"Atanas",
			"Atilio",
			"August",
			"Aureli",
			"Ayram ",
			"Ayrton",
			"Badia ",
			"Barbar",
			"Bartir",
			"Beatri",
			"Bela  ",
			"Belind",
			"Bereni",
			"Bernad",
			"Berta ",
			"Betâni",
			"Beth  ",
			"Beverl",
			"Betina",
			"Bianca",
			"Blanca",
			"Brenda",
			"Brigid",
			"Brigit",
			"Brisa ",
			"Bruna ",
			"Baldoc",
			"Basili",
			"Batist",
			"Benici",
			"Benito",
			"Benjam",
			"Bento ",
			"Bernar",
			"Billy ",
			"Boliva",
			"Bonifá",
			"Bosco ",
			"Brad  ",
			"Brás  ",
			"Brayan",
			"Brendo",
			"Breno ",
			"Brian ",
			"Bruce ",
			"Bruno ",
			"Cacild",
			"Camila",
			"Candid",
			"Carla ",
			"Carlot",
			"Carmel",
			"Carmem",
			"Carol ",
			"Carole",
			"Caroli",
			"Cassan",
			"Cassia",
			"Cassia",
			"Catari",
			"Cecile",
			"Cecíli",
			"Celene",
			"Celest",
			"Célia ",
			"Celina",
			"Chanta",
			"Charlo",
			"Chayll",
			"Chiara",
			"Cibele",
			"Cintia",
			"Clara ",
			"Claria",
			"Claris",
			"Cláudi",
			"Cleide",
			"Clélia",
			"Cléo  ",
			"Cleoni",
			"Cleoni",
			"Cleopa",
			"Cleuza",
			"Clotil",
			"Concei",
			"Consta",
			"Corina",
			"Cristi",
			"Cristi",
			"Caetan",
			"Caim  ",
			"Caiã  ",
			"Caio  ",
			"Caique",
			"Camilo",
			"Carlit",
			"Carlos",
			"Carmel",
			"Casimi",
			"Cassio",
			"Cauê  ",
			"Cécil ",
			"Célio ",
			"Celso ",
			"Cesar ",
			"Charle",
			"Chris ",
			"Christ",
			"Cid   ",
			"Cirano",
			"Cirilo",
			"Ciro  ",
			"Claudi",
			"Cleber",
			"Clésio",
			"Clície",
			"Clovis",
			"Conrad",
			"Consta",
			"Cornel",
			"Cosme ",
			"Crigor",
			"Cristi",
			"Cristi",
			"Dafnee",
			"Daisy ",
			"Dalia ",
			"Dalita",
			"Dalva ",
			"Daneli",
			"Daniel",
			"Debora",
			"Deidre",
			"Delia ",
			"Denise",
			"Diana ",
			"Dilma ",
			"Dinah ",
			"Dinora",
			"Dolore",
			"Domini",
			"Doris ",
			"Doroty",
			"Dulcin",
			"Dunia ",
			"Dan   ",
			"Daniel",
			"Danilo",
			"Dante ",
			"Damian",
			"Dario ",
			"David ",
			"Decio ",
			"Demétr",
			"Denis ",
			"Deocli",
			"Dercio",
			"Dereck",
			"Deusde",
			"Diego ",
			"Dieter",
			"Dilson",
			"Dimas ",
			"Diogo ",
			"Dionis",
			"Dirceu",
			"Doming",
			"Doriva",
			"Dougla",
			"Durval",
			"Edênia",
			"Edilia",
			"Edimar",
			"Edimer",
			"Edmagn",
			"Edith ",
			"Edna  ",
			"Eduard",
			"Edwirg",
			"Egle  ",
			"Elaine",
			"Elen  ",
			"Elena ",
			"Eleono",
			"Eliane",
			"Elida ",
			"Elide ",
			"Elisa ",
			"Elisab",
			"Elisia",
			"Elke  ",
			"Else  ",
			"Eloisa",
			"Elvira",
			"Elza  ",
			"Emanue",
			"Emilia",
			"Emmeli",
			"Eneida",
			"Erenil",
			"Erica ",
			"Erlain",
			"Ermini",
			"Estela",
			"Ester ",
			"Eugeni",
			"Eulali",
			"Eunice",
			"Eva   ",
			"Evange",
			"Evelyn",
			"Evelyn",
			"Ed    ",
			"Eder  ",
			"Edilso",
			"Ediral",
			"Edmils",
			"Ednei ",
			"Edson ",
			"Eduard",
			"Edvald",
			"Eivald",
			"Elias ",
			"Elieze",
			"Eliseu",
			"Eloy  ",
			"Elton ",
			"Emerso",
			"Emil  ",
			"Emilio",
			"Enio  ",
			"Estevã",
			"Eric  ",
			"Erinal",
			"Ernani",
			"Ernest",
			"Ettore",
			"Eugeni",
			"Eurico",
			"Euzebi",
			"Evair ",
			"Evandr",
			"Everal",
			"Fábia ",
			"Fabian",
			"Fabian",
			"Fabíol",
			"Fabríc",
			"Fany  ",
			"Fátima",
			"Fenici",
			"Fernan",
			"Filome",
			"Fiona ",
			"Flávia",
			"Flavia",
			"Flora ",
			"Franci",
			"Franci",
			"Franço",
			"Freder",
			"Fúlvia",
			"Fabian",
			"Fabian",
			"Fabio ",
			"Fabric",
			"Fausto",
			"Fauzer",
			"Felici",
			"Felici",
			"Felint",
			"Felipe",
			"Felix ",
			"Fernan",
			"Firmin",
			"Firmo ",
			"Flavio",
			"Franci",
			"Franz ",
			"Freder",
			"Fúlvio",
			"Gabrie",
			"Gardên",
			"Gerald",
			"German",
			"Geilsa",
			"Geny  ",
			"Georgi",
			"Gilda ",
			"Gina  ",
			"Giocon",
			"Giovan",
			"Giseld",
			"Gisele",
			"Gislai",
			"Giulia",
			"Giulia",
			"Giulli",
			"Gladis",
			"Glauci",
			"Glória",
			"Gorete",
			"Graça ",
			"Grace ",
			"Gracia",
			"Grazie",
			"Gudrun",
			"Gabrie",
			"Gaspar",
			"George",
			"Gerald",
			"Gerd  ",
			"German",
			"Gerson",
			"Gesual",
			"Getúli",
			"Giacom",
			"Gian  ",
			"Gianca",
			"Gianfr",
			"Gil   ",
			"Gilber",
			"Gilson",
			"Gilvan",
			"Giovan",
			"Glauco",
			"Gregor",
			"Guido ",
			"Guilhe",
			"Guilhe",
			"Gustav",
			"Hanna ",
			"Heide ",
			"Helen ",
			"Helena",
			"Helga ",
			"Helois",
			"Heriet",
			"Hilda ",
			"Hortên",
			"Harley",
			"Harold",
			"Hector",
			"Helder",
			"Heitor",
			"Helio ",
			"Helmut",
			"Henri ",
			"Herald",
			"Herber",
			"Hercul",
			"Hercul",
			"Herman",
			"Heron ",
			"Hidelb",
			"Homero",
			"Honori",
			"Horaci",
			"Hugo  ",
			"Humber",
			"Iasmim",
			"Idiene",
			"Ilana ",
			"Ilce  ",
			"Indira",
			"Inês  ",
			"Ingrid",
			"Imacul",
			"Inara ",
			"Ioland",
			"Ione  ",
			"Iracem",
			"Iraíde",
			"Irene ",
			"Irina ",
			"Iris  ",
			"Isabel",
			"Isabel",
			"Isador",
			"Isis  ",
			"Isolda",
			"Ivana ",
			"Ivani ",
			"Iverly",
			"Ivete ",
			"Ivna  ",
			"Ivonet",
			"Ivone ",
			"Izilda",
			"Ícaro ",
			"Igino ",
			"Igor  ",
			"Ilário",
			"Ilton ",
			"Inacio",
			"Irineu",
			"Isaac ",
			"Isaias",
			"Ismael",
			"Israel",
			"Iuri  ",
			"Ivan  ",
			"Ivich ",
			"Ivo   ",
			"Jacile",
			"Jade  ",
			"Jacque",
			"Jaimer",
			"Janain",
			"Jandin",
			"Janete",
			"Janey ",
			"Jaquel",
			"Jasmim",
			"Jeane ",
			"Jennif",
			"Joana ",
			"Joelle",
			"Johann",
			"Jordan",
			"Josefi",
			"Joselm",
			"Josie ",
			"Joyce ",
			"Jucile",
			"Judith",
			"Julia ",
			"Julian",
			"Juliet",
			"Jurema",
			"Jussar",
			"Jaime ",
			"Jair  ",
			"Jairo ",
			"James ",
			"Jason ",
			"Jean  ",
			"Jeffer",
			"Jeremi",
			"Jesus ",
			"João  ",
			"Joaqui",
			"Joel  ",
			"Joelmi",
			"Johane",
			"Johann",
			"John  ",
			"Johnny",
			"Jonas ",
			"Jonath",
			"Jorge ",
			"José  ",
			"Josual",
			"Josué ",
			"Judas ",
			"Julio ",
			"Juscel",
			"Justo ",
			"Kamill",
			"Karen ",
			"Karina",
			"Karyne",
			"Kate  ",
			"Kather",
			"Kátia ",
			"Kédma ",
			"Kelly ",
			"Kênia ",
			"Kriste",
			"Keid  ",
			"Keith ",
			"Kenned",
			"Kennet",
			"Kenzo ",
			"Kevin ",
			"Kleber",
			"Kleito",
			"Lais  ",
			"Lara  ",
			"Lariss",
			"Lavini",
			"Lauand",
			"Laura ",
			"Laylla",
			"Laysa ",
			"Leda  ",
			"Leila ",
			"Lenema",
			"Lenise",
			"Lenora",
			"Lesley",
			"Letíci",
			"Lidia ",
			"Liége ",
			"Ligia ",
			"Lilian",
			"Lilian",
			"Lilian",
			"Linda ",
			"Lindse",
			"Liney ",
			"Lis   ",
			"Lisete",
			"Lisley",
			"Lismar",
			"Lívia ",
			"Lolita",
			"Loreda",
			"Lorena",
			"Lorrai",
			"Louise",
			"Luana ",
			"Luce  ",
			"Lúcia ",
			"Lucian",
			"Lucian",
			"Lucien",
			"Lucila",
			"Lucíli",
			"Luciva",
			"Lucy  ",
			"Ludmil",
			"Ludice",
			"Luiza ",
			"Lurdes",
			"Luzia ",
			"Laerci",
			"Laerte",
			"Lauro ",
			"Leandr",
			"Leo   ",
			"Leon  ",
			"Leonar",
			"Levi  ",
			"Lineu ",
			"Livio ",
			"Lorenz",
			"Louis ",
			"Louriv",
			"Lucas ",
			"Lucian",
			"Lucio ",
			"Luigi ",
			"Luis  ",
			"LukeMa",
			"Madale",
			"Magali",
			"Magda ",
			"Maira ",
			"Maitê ",
			"Malka ",
			"Malú  ",
			"Manuel",
			"Mara  ",
			"Marcel",
			"Marcia",
			"Margar",
			"Margar",
			"Margar",
			"Maria ",
			"Marian",
			"Marian",
			"Maricy",
			"Mariel",
			"Márjor",
			"Marild",
			"Marile",
			"Marili",
			"Marili",
			"Marilu",
			"Marina",
			"Marine",
			"Maris ",
			"Marisa",
			"Marise",
			"Marist",
			"Marjor",
			"Marlen",
			"Marli ",
			"Marta ",
			"Martin",
			"Maruci",
			"Matild",
			"Maura ",
			"Mauree",
			"Mayã  ",
			"Mayara",
			"Maysa ",
			"Melani",
			"Melayn",
			"Meliss",
			"Milane",
			"Milena",
			"Milene",
			"Mircia",
			"Mirela",
			"Miriam",
			"Maciel",
			"Manoel",
			"Mantov",
			"Marcel",
			"Marcel",
			"Marcia",
			"Marcil",
			"Marcio",
			"Marco ",
			"Marcos",
			"Marian",
			"Marino",
			"Mario ",
			"Martin",
			"Massim",
			"Mateus",
			"Matias",
			"Mauric",
			"Mauro ",
			"Max   ",
			"Maximi",
			"Michel",
			"Miguel",
			"Milton",
			"Moacir",
			"Moises",
			"Mohsen",
			"Morris",
			"Murilo",
			"Naiara",
			"Nair  ",
			"Nancy ",
			"Natáli",
			"Natash",
			"Nayara",
			"Naylla",
			"Nayma ",
			"Nayra ",
			"Néia  ",
			"Neuza ",
			"Nicia ",
			"Nicole",
			"Nilda ",
			"Nilva ",
			"Nina  ",
			"Ninke ",
			"Nivia ",
			"Noemia",
			"Norma ",
			"Nuria ",
			"Narcis",
			"Natan ",
			"Natana",
			"Nelio ",
			"Nelson",
			"Nereo ",
			"Nevio ",
			"Newton",
			"Ney   ",
			"Nicola",
			"Nilton",
			"Nivald",
			"Odete ",
			"Odila ",
			"Odília",
			"Ofélia",
			"Olga  ",
			"Olides",
			"Olinda",
			"Olímpi",
			"Olivia",
			"Ondina",
			"Oraide",
			"Otávia",
			"Otília",
			"Odécio",
			"Odherb",
			"Odilon",
			"Odilso",
			"Odir  ",
			"Odoric",
			"Oduval",
			"Olavo ",
			"Olegár",
			"Olivie",
			"Onofre",
			"Orfeu ",
			"Orides",
			"Orland",
			"Omar  ",
			"Oscar ",
			"Osias ",
			"Osmar ",
			"Osni  ",
			"Osório",
			"Oswald",
			"Otacíl",
			"Otavia",
			"Otavio",
			"Otelo ",
			"Otoni ",
			"Otto  ",
			"Oton  ",
			"Ozeias",
			"Ozias ",
			"Paola ",
			"Patric",
			"Paula ",
			"Paulet",
			"Pedrin",
			"Pedrit",
			"Persia",
			"Perla ",
			"Petra ",
			"Petrúc",
			"Pia   ",
			"Pietra",
			"Pilar ",
			"Polian",
			"Prisci",
			"Próspe",
			"Pruden",
			"Pascoa",
			"Patric",
			"Paulo ",
			"Pedro ",
			"Perciv",
			"Peter ",
			"Petruc",
			"Pierlu",
			"Pierpa",
			"Piero ",
			"Pio   ",
			"Plácid",
			"Plinio",
			"Procop",
			"Quitér",
			"Quinca",
			"Quirin",
			"Raissa",
			"Raquel",
			"Rebeca",
			"Regina",
			"Rejane",
			"Renata",
			"Riane ",
			"Rita  ",
			"Robert",
			"Roclid",
			"Rogeri",
			"Romana",
			"Rosa  ",
			"Rosali",
			"Rosali",
			"Rosama",
			"Rosana",
			"Rosang",
			"Rosari",
			"Rosean",
			"Roseli",
			"Rosicl",
			"Rossan",
			"Ruth R",
			"Raimun",
			"Ralf  ",
			"Ramon ",
			"Randol",
			"Rárito",
			"Raul  ",
			"Regina",
			"Reinal",
			"Renato",
			"Ricard",
			"Robert",
			"Robson",
			"Rodney",
			"Rodrig",
			"Roger ",
			"Rogeri",
			"Romero",
			"Romeu ",
			"Romulo",
			"Ronald",
			"Roney ",
			"Roni  ",
			"Roque ",
			"Rossél",
			"Rubens",
			"Sabrin",
			"Salete",
			"Samant",
			"Samia ",
			"Samira",
			"Sandra",
			"Sarah ",
			"Sarina",
			"Selma ",
			"Sharon",
			"Sheeva",
			"Sheila",
			"Shirle",
			"Sibele",
			"Sibila",
			"Silmar",
			"Silvan",
			"Silvia",
			"Simone",
			"Sioma ",
			"Sofia ",
			"Solang",
			"Sonia ",
			"Sophia",
			"Soraia",
			"Stefan",
			"Stefan",
			"Stepha",
			"Stela ",
			"Suédia",
			"Sueli ",
			"Sumaia",
			"Susan ",
			"Suzana",
			"Suzel ",
			"Suzete",
			"Salvio",
			"Sandro",
			"Samir ",
			"Samuel",
			"Sante ",
			"Saul  ",
			"Sebast",
			"Sebast",
			"Sergio",
			"Sidney",
			"Silas ",
			"Silvai",
			"Silvan",
			"Silver",
			"Silvio",
			"Sócrat",
			"Stefan",
			"Sunny ",
			"Talia ",
			"Talita",
			"Tamara",
			"Tania ",
			"Tatian",
			"Telcil",
			"Teodor",
			"Teresa",
			"Téri  ",
			"Thais ",
			"Thauan",
			"Thayná",
			"Thelma",
			"Tiana ",
			"Tician",
			"Tricia",
			"Tônia ",
			"Tunia ",
			"Tarcis",
			"Teobal",
			"Teodor",
			"Thales",
			"Theo  ",
			"Theoph",
			"Theseo",
			"Thomas",
			"Timote",
			"Torqua",
			"Urania",
			"Ursula",
			"Ursuli",
			"Ubaldo",
			"Ubiraj",
			"Ulisse",
			"Ulpian",
			"Umbeli",
			"Umbert",
			"Urbano",
			"Uriel ",
			"Valdin",
			"Valent",
			"Valeri",
			"Valesk",
			"Vander",
			"Vaness",
			"Vani  ",
			"Vania ",
			"Vanusa",
			"Vera  ",
			"Verali",
			"Veridi",
			"Veroni",
			"Virgin",
			"Vitori",
			"Vivian",
			"Vivian",
			"Valdir",
			"Valmir",
			"Vander",
			"Vasco ",
			"Venânc",
			"Vences",
			"Vicent",
			"Vinici",
			"Vitor ",
			"Vivald",
			"Vladim",
			"Vlamir",
			"Xaukia",
			"Xênia ",
			"Yanna ",
			"Yasmin",
			"Yoland",
			"Yole  ",
			"Yone  ",
			"Yose Y",
			"Yan   ",
			"Yasson",
			"Yglési",
			"Yuki  ",
			"Yuri  ",
			"Yuso W",
			"Wanda ",
			"Wander",
			"Waness",
			"Wendy ",
			"Wilma ",
			"Wald  ",
			"Waldir",
			"Wallac",
			"Walter",
			"Wander",
			"Wando ",
			"Washin",
			"Weblen",
			"Wellin",
			"Welson",
			"Wesley",
			"Willia",
			"Wilson",
			"Wolf Z",
			"Zarifa",
			"Zelia ",
			"Zelind",
			"Zelita",
			"Zenaid",
			"Zenild",
			"Zenir ",
			"Zilá  ",
			"Zilda ",
			"Zilena",
			"Zilma ",
			"Zita  ",
			"Zora  ",
			"Zoraid",
			"Zulmir",
			"Zyndal",
			"Zacari",
			"Zélio ",
			"Zenóbi",
			"Zeus  ",
			"Zirald",
			"Zozimo"};
	
	public static VeiculoFactory getInstance() {
		return instance;
	}
	
	
	public List<Veiculo> geraVeiculo(int quantidadeVeiculos){
		LinkedList<Veiculo> list = new LinkedList<>();
		Random random = new Random();
		while(quantidadeVeiculos > 0){
			list.add(new Veiculo(getPlaca(), veiculo[random.nextInt(veiculo.length)], ThreadLocalRandom.current().nextInt(1950, 2017), nomes[random.nextInt(nomes.length)]));
			quantidadeVeiculos--;
		}
		return list;
	}
	
	
	public static String getPlaca(){
		int tam = letras.length;
		Random random = new Random();
		StringBuilder b = new StringBuilder();
		b.append(letras[random.nextInt(tam)]);
		b.append(letras[random.nextInt(tam)]);
		b.append(letras[random.nextInt(tam)]);
		b.append("-");
		b.append(random.nextInt(10));
		b.append(random.nextInt(10));
		b.append(random.nextInt(10));
		return b.toString();
	}
}
